# Generated by Django 2.1.2 on 2019-05-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dev',
            name='create_time',
        ),
    ]
